/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/facilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Facilities */
        get: operations["list_facilities_facilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/facilities/{facility_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Facility */
        get: operations["get_facility_facilities__facility_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/facilities/{facility_id}/ai-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Ai Summary */
        post: operations["get_ai_summary_facilities__facility_id__ai_summary_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/facilities/{facility_id}/legal-memo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Legal Memo */
        post: operations["get_legal_memo_facilities__facility_id__legal_memo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inspectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Inspectors */
        get: operations["list_inspectors_inspectors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inspectors/{inspector_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Inspector */
        get: operations["get_inspector_inspectors__inspector_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard Stats */
        get: operations["get_dashboard_stats_dashboard_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/violations/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Violations */
        get: operations["search_violations_violations_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/proxy-pdf/{inspection_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Proxy Pdf */
        get: operations["proxy_pdf_documents_proxy_pdf__inspection_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AISummaryOut */
        AISummaryOut: {
            /** Summary */
            summary: string;
        };
        /** DashboardStatsOut */
        DashboardStatsOut: {
            /** Total Facilities */
            total_facilities: number;
            /** Total Inspections */
            total_inspections: number;
            /** Total Violations */
            total_violations: number;
            /** Severity Distribution */
            severity_distribution: {
                [key: string]: number;
            };
            /** Top Violating Facilities */
            top_violating_facilities: {
                [key: string]: unknown;
            }[];
            /** Top States */
            top_states: {
                [key: string]: unknown;
            }[];
            /** Top Inspectors */
            top_inspectors: {
                [key: string]: unknown;
            }[];
            /** Risk Flags Distribution */
            risk_flags_distribution: {
                [key: string]: number;
            };
            /** Inspections Per Month */
            inspections_per_month: {
                [key: string]: unknown;
            }[];
        };
        /** FacilityDetailOut */
        FacilityDetailOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Customer Id */
            customer_id: string | null;
            /** Certificate Number */
            certificate_number: string | null;
            /** License Type */
            license_type: string | null;
            /** License Status */
            license_status: string | null;
            /** Address */
            address: string | null;
            /** City */
            city: string | null;
            /** State */
            state: string | null;
            /** Zip Code */
            zip_code: string | null;
            /** County */
            county: string | null;
            /** Licensed Animal Limit */
            licensed_animal_limit: number | null;
            risk_flags: components["schemas"]["RiskFlagsOut"];
            /** Inspections */
            inspections?: components["schemas"]["InspectionOut"][];
        };
        /** FacilityListItemOut */
        FacilityListItemOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Customer Id */
            customer_id: string | null;
            /** Certificate Number */
            certificate_number: string | null;
            /** License Type */
            license_type: string | null;
            /** License Status */
            license_status: string | null;
            /** Address */
            address: string | null;
            /** City */
            city: string | null;
            /** State */
            state: string | null;
            /** Zip Code */
            zip_code: string | null;
            /** County */
            county: string | null;
            /** Licensed Animal Limit */
            licensed_animal_limit: number | null;
            /**
             * Total Inspections
             * @default 0
             */
            total_inspections: number;
            /**
             * Total Violations
             * @default 0
             */
            total_violations: number;
            /** Last Inspection Date */
            last_inspection_date?: string | null;
        };
        /** FacilityListOut */
        FacilityListOut: {
            /** Total */
            total: number | null;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Cursor */
            cursor?: string | null;
            /** Results */
            results: components["schemas"]["FacilityListItemOut"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InspectionOut */
        InspectionOut: {
            /** Id */
            id: number;
            /** Facility Id */
            facility_id?: number | null;
            /** Facility Name */
            facility_name?: string | null;
            /** Facility State */
            facility_state?: string | null;
            /** Inspection Date */
            inspection_date: string | null;
            /** Inspection Type */
            inspection_type: string | null;
            /** Inspector Name */
            inspector_name: string | null;
            /** Inspector Id */
            inspector_id: string | null;
            /** Violations Found */
            violations_found: boolean | null;
            /** Violation Count */
            violation_count: number | null;
            /** Source Pdf */
            source_pdf: string | null;
            /** Source Pdf Path */
            source_pdf_path: string | null;
            /** Violations */
            violations?: components["schemas"]["ViolationOut"][];
            /** Inventory */
            inventory?: components["schemas"]["InventoryOut"][];
        };
        /** InspectorDetailOut */
        InspectorDetailOut: {
            /** Inspector Id */
            inspector_id: string | null;
            /** Inspector Name */
            inspector_name: string | null;
            /** Total Inspections */
            total_inspections: number;
            /** Non Compliance Rate */
            non_compliance_rate: number;
            /** Primary State */
            primary_state: string | null;
            /** Regional Average Rate */
            regional_average_rate: number | null;
            /** Anomaly Flag */
            anomaly_flag: boolean;
            /** Inspections */
            inspections?: components["schemas"]["InspectionOut"][];
        };
        /** InspectorListOut */
        InspectorListOut: {
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Results */
            results: components["schemas"]["InspectorOut"][];
        };
        /** InspectorOut */
        InspectorOut: {
            /** Inspector Id */
            inspector_id: string | null;
            /** Inspector Name */
            inspector_name: string | null;
            /** Total Inspections */
            total_inspections: number;
            /** Non Compliance Rate */
            non_compliance_rate: number;
            /** Primary State */
            primary_state: string | null;
            /** Regional Average Rate */
            regional_average_rate: number | null;
            /** Anomaly Flag */
            anomaly_flag: boolean;
        };
        /** InventoryOut */
        InventoryOut: {
            /** Id */
            id: number;
            /** Scientific Name */
            scientific_name: string | null;
            /** Common Name */
            common_name: string | null;
            /** Count */
            count: number | null;
            /** Source Pdf */
            source_pdf: string | null;
        };
        /** LegalMemoOut */
        LegalMemoOut: {
            /** Memo */
            memo: string;
        };
        /** RiskFlagsOut */
        RiskFlagsOut: {
            /**
             * Has High Direct Violations
             * @default false
             */
            has_high_direct_violations: boolean;
            /**
             * Has Repeated Indirect
             * @default false
             */
            has_repeated_indirect: boolean;
            /**
             * Animal Limit Exceeded
             * @default false
             */
            animal_limit_exceeded: boolean;
            /**
             * Is Teachable Heavy
             * @default false
             */
            is_teachable_heavy: boolean;
            /**
             * Recent Inventory Spike
             * @default false
             */
            recent_inventory_spike: boolean;
            /**
             * Score
             * @default 0
             */
            score: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ViolationOut */
        ViolationOut: {
            /** Id */
            id: number;
            /** Severity */
            severity: string | null;
            /** Section */
            section: string | null;
            /** Description */
            description: string | null;
            /** Source Pdf */
            source_pdf: string | null;
            /** Source Page */
            source_page: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_facilities_facilities_get: {
        parameters: {
            query?: {
                name?: string | null;
                state?: string | null;
                license_type?: string | null;
                has_violations?: boolean | null;
                species?: string | null;
                exceeds_animal_limit?: boolean | null;
                high_direct_violations?: boolean | null;
                inventory_spike?: boolean | null;
                severity?: string | null;
                sort_by?: string;
                limit?: number;
                offset?: number;
                cursor?: string | null;
                include_total?: boolean;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacilityListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_facility_facilities__facility_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                facility_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacilityDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ai_summary_facilities__facility_id__ai_summary_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                facility_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AISummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_legal_memo_facilities__facility_id__legal_memo_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                facility_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegalMemoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_inspectors_inspectors_get: {
        parameters: {
            query?: {
                state?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InspectorListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_inspector_inspectors__inspector_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                inspector_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InspectorDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_stats_dashboard_stats_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardStatsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_violations_violations_search_get: {
        parameters: {
            query?: {
                query?: string | null;
                severity?: string | null;
                section?: string | null;
                facility_id?: number | null;
                state?: string | null;
                date_start?: string | null;
                date_end?: string | null;
                sort_by?: string;
                limit?: number;
                offset?: number;
                include_total?: boolean;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    proxy_pdf_documents_proxy_pdf__inspection_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                inspection_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
