/**
 * Type-safe API client generated from the OpenAPI spec.
 * Types are auto-generated by `openapi-typescript` from backend/openapi.json.
 * To regenerate: `npx openapi-typescript ../backend/openapi.json -o src/services/api.d.ts`
 *
 * @typedef {import("./api.d.ts").paths} Paths
 */
import createClient from "openapi-fetch";

const BASE_URL = import.meta.env.VITE_API_URL || "http://localhost:8000";
const API_KEY = import.meta.env.VITE_API_KEY;

/** @type {import("openapi-fetch").Client<Paths>} */
const client = createClient({

  baseUrl: BASE_URL,
  headers: API_KEY ? { "X-API-Key": API_KEY } : {},
});

// ── Facilities ──────────────────────────────────────────────────────────────

export async function searchFacilities(params = {}) {
  const { data, error } = await client.GET("/facilities", { params: { query: params } });
  if (error) throw error;
  return data;
}

export async function getFacility(id) {
  const { data, error } = await client.GET("/facilities/{facility_id}", {
    params: { path: { facility_id: id } },
  });
  if (error) throw error;
  return data;
}

// ── Inspectors ──────────────────────────────────────────────────────────────

export async function getInspectors(params = {}) {
  const { data, error } = await client.GET("/inspectors", { params: { query: params } });
  if (error) throw error;
  return data;
}

export async function getInspector(id) {
  const { data, error } = await client.GET("/inspectors/{inspector_id}", {
    params: { path: { inspector_id: id } },
  });
  if (error) throw error;
  return data;
}

// ── Dashboard ────────────────────────────────────────────────────────────────

export async function getDashboardStats() {
  const { data, error } = await client.GET("/dashboard/stats");
  if (error) throw error;
  return data;
}

// ── AI ────────────────────────────────────────────────────────────────────────

export async function generateAISummary(id) {
  const { data, error } = await client.POST("/facilities/{facility_id}/ai-summary", {
    params: { path: { facility_id: id } },
  });
  if (error) throw error;
  return data;
}

export async function generateLegalMemo(id) {
  const { data, error } = await client.POST("/facilities/{facility_id}/legal-memo", {
    params: { path: { facility_id: id } },
  });
  if (error) throw error;
  return data;
}

// Raw client export for one-off calls
export default client;
