/**
 * Type-safe API client generated from the OpenAPI spec.
 * Types are auto-generated by `openapi-typescript` from backend/openapi.json.
 * To regenerate: `npx openapi-typescript ../backend/openapi.json -o src/services/api.d.ts`
 *
 * @typedef {import("./api.d.ts").paths} Paths
 */
import createClient from "openapi-fetch";
import supabase from "../lib/supabase";

const BASE_URL = import.meta.env.VITE_API_URL || "http://localhost:8000";

/** @type {import("openapi-fetch").Client<Paths>} */
const client = createClient({
  baseUrl: BASE_URL,
});

client.use({
  async onRequest({ request }) {
    try {
      const { data: { session } } = await supabase.auth.getSession();
      if (session?.access_token) {
        request.headers.set("Authorization", `Bearer ${session.access_token}`);
      }
    } catch (e) {
      console.error("Failed to inject auth header", e);
    }
    return request;
  }
});

// ── Facilities ──────────────────────────────────────────────────────────────

export async function searchFacilities(params = {}) {
  const { data, error } = await client.GET("/facilities", { params: { query: params } });
  if (error) throw error;
  return data;
}

export async function getFacility(id) {
  const { data, error } = await client.GET("/facilities/{facility_id}", {
    params: { path: { facility_id: id } },
  });
  if (error) throw error;
  return data;
}

export async function getFacilityDossierSummary(id) {
  const { data, error } = await client.GET("/facilities/{facility_id}/dossier-summary", {
    params: { path: { facility_id: id } },
  });
  if (error) throw error;
  return data;
}

export async function getFacilityInspections(id) {
  const { data, error } = await client.GET("/facilities/{facility_id}/inspections", {
    params: { path: { facility_id: id } },
  });
  if (error) throw error;
  return data;
}

// ── Inspectors ──────────────────────────────────────────────────────────────

export async function getInspectors(params = {}) {
  const { data, error } = await client.GET("/inspectors", { params: { query: params } });
  if (error) throw error;
  return data;
}

export async function getInspector(id) {
  const { data, error } = await client.GET("/inspectors/{inspector_id}", {
    params: { path: { inspector_id: id } },
  });
  if (error) throw error;
  return data;
}

// ── Dashboard ────────────────────────────────────────────────────────────────

export async function getDashboardStats() {
  const { data, error } = await client.GET("/dashboard/stats");
  if (error) throw error;
  return data;
}

// ── AI ────────────────────────────────────────────────────────────────────────

export async function generateAISummary(id) {
  const { data, error } = await client.POST("/facilities/{facility_id}/ai-summary", {
    params: { path: { facility_id: id } },
  });
  if (error) throw error;
  return data;
}

export async function generateLegalMemo(id) {
  const { data, error } = await client.POST("/facilities/{facility_id}/legal-memo", {
    params: { path: { facility_id: id } },
  });
  if (error) throw error;
  return data;
}

export async function getAISummary(id) {
  const { data, error } = await client.GET("/facilities/{facility_id}/ai-summary", {
    params: { path: { facility_id: id } },
  });
  if (error) throw error;
  return data;
}

export async function getLegalMemo(id) {
  const { data, error } = await client.GET("/facilities/{facility_id}/legal-memo", {
    params: { path: { facility_id: id } },
  });
  if (error) throw error;
  return data;
}

export async function searchViolations(params = {}) {
  const { data, error } = await client.GET("/violations/search", { params: { query: params } });
  if (error) throw error;
  return data;
}

export async function searchEnforcement(params = {}) {
  const { data, error } = await client.GET("/enforcement", { params: { query: params } });
  if (error) throw error;
  return data;
}

export async function getEnforcement(id) {
  const { data, error } = await client.GET("/enforcement/{id}", {
    params: { path: { id } },
  });
  if (error) throw error;
  return data;
}

export async function getFacilityEnforcement(facilityId) {
  const { data, error } = await client.GET("/facilities/{facility_id}/enforcement", {
    params: { path: { facility_id: facilityId } },
  });
  if (error) throw error;
  return data;
}

// Raw client export for one-off calls
export default client;
